// Code generated by go-swagger; DO NOT EDIT.

// Package restapi IgnitionServer
//
//  Ignition Server
//  Schemes:
//    http
//  Host: api.openshift.com
//  BasePath: /api/ignition-server/v1
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
