// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Ignition Server",
    "title": "IgnitionServer",
    "version": "1.0.0"
  },
  "host": "api.openshift.com",
  "basePath": "/api/ignition-server/v1",
  "paths": {
    "/config/{clusterId}/{role}": {
      "get": {
        "tags": [
          "ignition-server"
        ],
        "summary": "Get config by cluster id and role",
        "operationId": "GetConfig",
        "parameters": [
          {
            "type": "string",
            "description": "Cluster id",
            "name": "clusterId",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "Node role",
            "name": "role",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Config file in json format",
            "schema": {
              "$ref": "#/definitions/config_params"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "config_params": {
      "type": "object",
      "properties": {
        "clusterId": {
          "type": "string",
          "example": "igal-test1"
        },
        "name": {
          "type": "string",
          "example": "doggie"
        },
        "role": {
          "type": "string",
          "example": "bootstrap"
        },
        "url": {
          "type": "string",
          "example": "https://10.12.1.150"
        }
      }
    }
  },
  "tags": [
    {
      "description": "Ignition Server",
      "name": "Ignition Server"
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Ignition Server",
    "title": "IgnitionServer",
    "version": "1.0.0"
  },
  "host": "api.openshift.com",
  "basePath": "/api/ignition-server/v1",
  "paths": {
    "/config/{clusterId}/{role}": {
      "get": {
        "tags": [
          "ignition-server"
        ],
        "summary": "Get config by cluster id and role",
        "operationId": "GetConfig",
        "parameters": [
          {
            "type": "string",
            "description": "Cluster id",
            "name": "clusterId",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "Node role",
            "name": "role",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Config file in json format",
            "schema": {
              "$ref": "#/definitions/config_params"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "config_params": {
      "type": "object",
      "properties": {
        "clusterId": {
          "type": "string",
          "example": "igal-test1"
        },
        "name": {
          "type": "string",
          "example": "doggie"
        },
        "role": {
          "type": "string",
          "example": "bootstrap"
        },
        "url": {
          "type": "string",
          "example": "https://10.12.1.150"
        }
      }
    }
  },
  "tags": [
    {
      "description": "Ignition Server",
      "name": "Ignition Server"
    }
  ]
}`))
}
