// Code generated by go-swagger; DO NOT EDIT.

package ignition_server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetConfigParams creates a new GetConfigParams object
// no default values defined in spec.
func NewGetConfigParams() GetConfigParams {

	return GetConfigParams{}
}

// GetConfigParams contains all the bound params for the get config operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetConfig
type GetConfigParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Cluster id
	  Required: true
	  In: path
	*/
	ClusterID string
	/*Node role
	  Required: true
	  In: path
	*/
	Role string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetConfigParams() beforehand.
func (o *GetConfigParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rClusterID, rhkClusterID, _ := route.Params.GetOK("clusterId")
	if err := o.bindClusterID(rClusterID, rhkClusterID, route.Formats); err != nil {
		res = append(res, err)
	}

	rRole, rhkRole, _ := route.Params.GetOK("role")
	if err := o.bindRole(rRole, rhkRole, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindClusterID binds and validates parameter ClusterID from path.
func (o *GetConfigParams) bindClusterID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.ClusterID = raw

	return nil
}

// bindRole binds and validates parameter Role from path.
func (o *GetConfigParams) bindRole(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.Role = raw

	return nil
}
