// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ConfigParams config params
// swagger:model config_params
type ConfigParams struct {

	// cluster Id
	ClusterID string `json:"clusterId,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// role
	Role string `json:"role,omitempty"`

	// url
	URL string `json:"url,omitempty"`
}

// Validate validates this config params
func (m *ConfigParams) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ConfigParams) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConfigParams) UnmarshalBinary(b []byte) error {
	var res ConfigParams
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
